#!/bin/sh
APCOM='app33053049'
CYAN='\033[0;36m'
NC='\033[0m' # No Color
printf "${CYAN}*** While downloading move fresh [ap].user to ~/ap_mongo/refresh/apcom/users.bson${NC}\n"
printf "${CYAN}CMD: Dump analytics.data${NC}\n"
mongodump -h $1 -d $2 -u heroku -p $3 -o ~/ap_mongo/refresh -c issues
mongodump -h $1 -d $2 -u heroku -p $3 -o ~/ap_mongo/refresh -c views
mongodump -h $1 -d $2 -u heroku -p $3 -o ~/ap_mongo/refresh -c events
# mongodump -h $1 -d $2 -u heroku -p $3 -o ~/ap_mongo/refresh -c impressions
printf "${CYAN}CMD: Import /refresh/${2}/*.bson${NC}\n"
mongorestore --drop --db airpair_dev_analytics ~/ap_mongo/refresh/$2
printf "${CYAN}CMD: CP latest [${APCOM}].users to /refresh/apcom/users${NC}\n"
cp ~/ap_mongo/app33053049/users.bson ~/ap_mongo/refresh/apcom/users.bson
printf "${CYAN}CMD: Import latest [apcom].users${NC}\n"
mongorestore --drop --db airpair_dev_analytics ~/ap_mongo/refresh/apcom
cmd/guard-user-check
