#!/bin/sh
killall node
if [ "$1" = "" ]; then
  ./cmd/build/dev;
elif [ "$1" = "--dist" ]; then
  ./cmd/build/dev;
elif [ "$1" = "--dist" ]; then
  ./cmd/build/dist;
fi
node ../static/index.js &
cd cmd;
gulp;
