#!/bin/sh
CMD="\033[0;36mcmd/setup:\033[0m ";

printf "${CMD}CLEAN npm modules /node_modules\n"
rm package-lock.json
rm -rf node_modules

printf "${CMD}LINK local npm modules /node_modules\n"
npm link screamjs
npm link honeycombjs
npm link meanair-build
printf "${CMD}Installing npm packages (could take a minute)\n"
npm install;

printf "${CMD}SYMLINK meanair-build/node_modules/gulp\n"
cd node_modules;
ln -nsf meanair-build/node_modules/gulp
cd ../;

# printf "${CMD}SYMLINK meanair-build/build/cmd/${NC}\n"
# mkdir -p cmd/build;
# cd cmd/build;
# for l in $(find . -type l); do unlink $l;done;
# for f in $(ls -d ../../node_modules/meanair-build/cmd/build/*); do ln -nsf $f;done;
# cd ../../;

printf "${CMD}SETUP git hooks${NC}\n"
rm -rf .git/hooks;
mkdir .git/hooks;
cd .git/hooks;
ln -nsf ../../cmd/dev/git-hook/pre-push;
cd ../../;

# bower install;
# printf "${CMD}COPY JS web/components${NC}\n"
# rm -rf web/components;
# mkdir -p web/components;
# cd web/components;
# for f in $(ls ../../../static/src/js/libs);do cp ../../../static/src/js/libs/$f $f;done;
# cd ../../;
