#!/bin/sh
CYAN='\033[0;36m'
NC='\033[0m' # No Color
CMD="${CYAN}CMD/deploy: ${NC}";
# printf "${CMD}: Move dist js\n"
# cd web/dist
# for l in $(ls -d js/*); do mv $l ../../../static/host/archive/apcom/$l;done;
# rm -rf js
# for l in $(ls -d css/*); do mv $l ../../../static/host/archive/apcom/$l;done;
# rm -rf css
# cd ../../;
